services:
  phocker:
    container_name: phocker
    build: ./compose
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - "./app:/var/www/html"
      - "./compose/php.ini:/etc/php83/conf.d/00_php.ini"

