services:
  phocker:
    container_name: phocker
    build: ./compose
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - "./app:/var/www/html"
      - "./compose/php.ini:/etc/php83/conf.d/00_php.ini"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.drawio.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.drawio.entrypoints=websecure"
      - "traefik.http.routers.drawio.tls.certresolver=myresolver"
    networks:
      web:
networks:
  web:
    name: web
    external: true
